version: "3"
services:
  server:
    image: debs2019challenge/benchmark-server
    container_name: benchmark-server
    restart: always
    volumes:
      - ./dataset:/dataset

    networks:
          - bench

  client:
    container_name: client-app
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      BENCHMARK_SYSTEM_URL: 'server'

    depends_on:
      - server

    networks:
          - bench
    #tty: true


networks:
    bench: {}
